# -*- coding: utf-8 -*-
"""(module)6주차_2021-10-07.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12GCkd2fJ3Jx6e7CaWOr6QGLG_aVrf0Rz

# 모듈(module)

## 모듈과 import 함수
+ 파이썬 함수나 변수 또는 클래스들을 모아 놓은 스크립트 파일
+ 파이썬은 수많은 개발자들에 의해서 개발된 많은 모듈이 있음.
+ 사용할 때에는 모듈 이름에 점(.)을 찍은 후 모듈 안의 구성요소를 작성.
+ **파이썬 표준 라이브러리**: 파이썬 설치와 함께 제공되는 모듈

## import ~ as
"""

# 로또 번호 만들기 1
import random as rd
lottoList = list(range(1, 46))
rd.shuffle(lottoList) # 임의로 섞기
lottoList = lottoList[:6] # 앞 부분 6개만 선택
lottoList.sort() # 오름 차순 정렬
#내림차순
#b.sort(reverse=True)
print("이번주의 추천 로또 번호는 {}입니다.".format(lottoList))


# 로또 번호 만들기 2
import random as rd
lottoList = list(range(1, 46))
lottoList = rd.sample(lottoList, 6) # 임의의 6개 추출(샘플링)
lottoList.sort()
print("이번주의 추천 로또 번호는 {}입니다.".format(lottoList))

# turtle
import turtle as t
t.setup(width = 400, height = 400)
# for i in range(200):
#   t.forward(i)
#   t.left(93)

# t.done

