# -*- coding: utf-8 -*-
"""(print,str,bool)1주차_2021-09-06,09.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1F67leToUDBsu0TQPSRuvnzoQlOzPe92B
"""

#2021-09-06(월): 1주차 1차시 수업
#과제1
print('당신의 학과는 :')
major = "영어영문학과"
print('내가 소속한 학과는', major, '입니다.')

#변수 이용1
horizon = 4.5 #가로
vertical =9 #세로
print('사각형 넓이는', horizon * vertical, 'cm2 이다')

#변수 이용2_과제2
radius = 4.5
print('원의 넓이는', radius * radius * 3.14)
print('원의 둘레는', 3.14 * radius * 2.0)

#과제3_3개의 정수를 키보드로 입력 받아서 평균 출력
a = 3
b = 5
c = 7
mean = (a+b+c)/3
print('입력한 수', a, ',', b, ',', c, ',', '의 평균은',mean, '이다.' )


#input()

#연산_실습
g = 5
h = 3
print(g + h) #더하기
print(g - h) #빼기
print(g * h) #곱셈
print(g / h) #나눗셈
print(g // h) #몫
print(g % h) #나머지
print(5 ** 3) #거듭제곱
7//6
7%6
7**6

#error_delete
my_age =  22
my_height = int('177') #''제거 혹은 int 추가해서 자료형 명시
my_age = my_height + 1
my_height = my_height + 1
print(my_age, my_height)

#문자열
txt3 = "친구가 \"햇님이 좋아!\"라고 말했다"
txt3

#부동소수점수
print(0.1+0.1+0.1==0.3)
0.1+0.1+0.1

#할당연산자
num1 = num2 = num3 = 300 #다중 할당문
print(num1, num2, num3)
num4, num5 = 300, 400 #동시 할당문
print(num4, num5)

#2021-09-09(목): 1주차 2차시 수업
#문자열
txt3 = "친구가 \"햇님이 좋아!\"라고 말했다"
txt2 = '친구가 "햇님이 좋아!"라고 말했다.'
txtN = '오늘은 \'날씨\'가 진짜 좋다'
txt3
txt2
txt5 = 'banana\nnapple\nnorange'
txt5
print(txt5)

txt3 = "친구가 \"햇님이 좋아!\"라고 말했다"
txt2 = '친구가 "햇님이 좋아!"라고 말했다.'

txt2
txt5 = 'banana\nnapple\nnorange'
txt5
print(txt3)
print(txt2)
print(txtN)
print(txt5)

#비교연산자
a, b = 100, 200
print(a == b)
print(a != b)
print(a > b)
print(a < b)
print(a >= b)

#논리 연산자
10 > 20
10 < 20
#bool 자료형에 참과 거짓이 있다. 
#문자열, 리스트, 튜플, 딕셔너리 등의 값이 비어 있으면(" ", [ ], ( ), { }) 거짓이 된다. 
#당연히 비어있지 않으면 참이 된다. 
#숫자에서는 그 값이 0일 때 거짓이 된다. None은 거짓을 뜻한다는 것만 알아두자.
print(bool(9<6)) # False
print(bool(9>6)) # True
print(bool(-1)) # True
print(bool(0)) # False
print(bool(None)) # False
print(bool({})) # False
print(bool([2,3,4])) #True

#2진수 반환
print(bin(116))
print(bin(9))
print(bin(10))
print(9 & 10)
print(bin(8))
print(bin(4))
#shift
print(bin(4))
print(4 >> 1)
print(bin(2))
print(4 << 1)
print(bin(8))
print(bin(5))
print(5 >> 2)
print(bin(1))

