# -*- coding: utf-8 -*-
"""(self-review)21-10-17.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZxFX5N1jCIR8qbnk3sVzluvGI79QCyK0
"""

num = int(input("숫자"))
for i in range(2, num+1):
  print(i,"단 시작")
  for t in range(1, 10):
    y = i * t
    print(i, "x", t, "=", y)

grade = list(map(int,input("점수 입력").split()))
#mean
c = 0 
for i in grade:
  c = c + i
  result = c /len(grade)
print(result)

# (variance)은 관측값에서 평균을 뺀 값을 제곱하고, 그것을 모두 더한 후 전체 개수로 나눠서 구한다. 즉, 차이값의 제곱의 평균이다. 
# variance
s = 0
for i in grade:
  s = s + (i- result)**2
  variance = s /len(grade)
print(variance)

for i in grade:
  if i >= 70:
    print("PASS")
  else:
    print("NON-PASS")



nums= [1,9,9,9,0,4,1,3,2,0,1,8,0,1,9,1]
for i in range(len(nums)):
  k = len(nums) - i
  for z in range(1, k):
    if nums[z-1] >= nums[z]:
      temp = nums[z-1]
      nums[z-1] = nums[z]
      nums[z] = temp
print(*nums,sep='\n')

