# -*- coding: utf-8 -*-
"""(stack)_9주차_21.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13q7RDOstmdbtsuJ0Z1rMFFHQrb4qQL18
"""

top = []
def isEmpty():
  return len(top) == 0

def push(item):
  top.append(item)

def pop():
  if not isEmpty():
    return top.pop(-1)

def peek():
  if not isEmpty():
    return top[-1]

def size():
  return len(top)

def clear():
  global top
  top = []

for i in range(1,6):
  push(i)

print(top)

print(" pop() -->", pop())
print(" pop() -->", pop())

print(top)

push("홍길동")
push("이순신")

print(top)

print(" pop() -->", pop())

print(top)

# stack 구현 - 클래스
# class Stack:
def __init__(self):
  self.top = []

def isEmpty(self):
  return len(self.top) == 0
def size(self):
  return len(self.top)
def clear(self):
  self.top = []

def pop(self):
  if not self.isEmpty():
    return self.top.pop(-1)
def peek(self):
  if not self.isEmpty():
    return self.top[-1]
def push(self,item):
  self.top.append(item)

# stack의 활용
# import Stack
odd = Stack()
even = Stack()

for i in range(10):
  if i%2 == 0:
    even.push(i)
  else:
    odd.push(i)

print(even)
print(odd)

even.pop()
odd.pop()

print(even)

print(odd)

even.push('이순신')

print(even)

