# -*- coding: utf-8 -*-
"""(star)renew_hw2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10kfPGs9Kzw6JNSWOYHmxn3aU6K_jzrKg
"""

#practice
for i in range (5):
  for z in range (5):
    print('*', end='')
  print()

#1. 별 삼각형_순차적으로 출력(방법1)
for i in range (5):
  for h in range (5):
    if h <= i:
      print ('*', end='')
  print()

#1. 별 삼각형_순차적으로 출력(방법2)
for i in range(1,6):
  print('*'*i)

for i in range(1, 6):
  print("*"*i)

#1. 문제 도움받은 설명
for i in range(5):        # 0부터 4까지 5번 반복. 세로 방향
    for j in range(5):    # 0부터 4까지 5번 반복. 가로 방향
        if j <= i:                # 세로 방향 변수 i만큼
            print('*', end='')    # 별 출력. end에 ''를 지정하여 줄바꿈을 하지 않음
    print()    # 가로 방향으로 별을 다 그린 뒤 다음 줄로 넘어감
               # (print는 출력 후 기본적으로 다음 줄로 넘어감)

#2. 별 역삼각형_많은 수부터 나오도록 
for i in range(1,6):
  print('*'*(6-i))

for i in range(1, 6):
  print("*"*(6-i))

# 3. 별 우측 삼각형
for i in range(1,6):
  print(' '*(5-i), end ='')
  print('*'*i)

for i in range (1, 6):
  print(' '*(6-i), end = '')
  print('*'*i)

# 4. # 구구단 입력받기 + 2단 이상 구구단을 입력 받았는지 확인
n = int(input('출력을 원하는 구구단을 입력하세요 : '))
if n >= 2 :
  print('2단부터', n, '단을 출력합니다')
else :
    print("2단 이상 입력해주세요.")

# 입력 받은 값의 구구단 출력
for i in range (2, n+1):
    print(i, '단 시작합니다')
    for y in range (1,10) :
      print(i, "x", y, "=", i*y)

# 21-10-18추가코딩
num = int(input("숫자"))
for i in range(2, num+1):
  print(i,"단 시작")
  for t in range(1, 10):
    y = i * t
    print(i, "x", t, "=", y)

# 5. 본인이 원하는 학생 수만큼의 점수를 입력 받아 평균, 분산을 구하고 
# 평균이 70점 이상일때 '합격'출력하고, 70점 미만일 때 '불합격'을 출력
# 5-1) 평균
grade = list(map(int, input('학생들의 점수를 입력하세요:').split()))
avr=0
for i in grade:
  avr+= i
print(avr/len(grade))

# 5-2) 분산
grade = list(map(int, input('학생들의 점수를 입력하세요:').split()))
vsum=0
for i in grade:
  vsum = vsum + (i - sum(grade)/len(grade))**2
variance = vsum / len(grade)
print(variance)

# 5-3) 합격, 불합격 출력
grade = list(map(int, input('학생들의 점수를 입력하세요:').split()))

if sum(grade)/len(grade) >= 70:
  print('합격')
else :  
  print('불합격')

# 6. 원리금, 이자 
# process 1) 100만원 이상 원금, 이율, 기간 입력받기
# process 2) 1)에 맞는 조건 입력받으면, 원리금(원금+이자)출력.
# 출력예시에서 원리금을 출력하고 있음 -> 즉, 원금+이자의 합계를 출력하는 것이 문제의 요점.
# 복리 계산 공식:  현재가치 * ((1+금리) ** 기간)
org = int(input("원금(단위:원)을 입력하세요 : "))
if org >= 1000000 :
    perc = int(input("이율(%)을 입력하세요 : "))
    year = int(input("기간(년)을 입력하세요 : "))
    PnI = org * ((1+perc*0.01)**year)
    print(PnI)
else :
    print("잘못된 입력입니다. 1,000,000원 이상 입력해주세요.")

# 두 변수 값 맞바꾸는 방법
>>> a = 10
>>> b = 20
>>> temp = a               # a 값을 temp에 저장   (temp = 10)
>>> a = b                  # b 값을 a에 저장      (a = 20)
>>> b = temp               # temp 값을 b에 저장   (b = 10)
>>> print(a, b)
20 10

#7. 생년월일, 학번 정렬
num = [1,9,9,9,0,4,1,3,2,0,1,8,0,1,9,1]

for i in range(len(num)):
  h = len(num) - i
  for z in range(1, h):
      if num[z-1] >= num[z]:
        temp = num[z-1]
        num[z-1] = num[z]
        num[z] = temp
print(*num,sep='\n')