# -*- coding: utf-8 -*-
"""(제어문)2주차_2021-09-13,16.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ydx6sxEKZQN50nYgh_lqxbB7z89iZvJq

## 2021-09-13(월) 2주차-1차시
"""

#제어문
#for문, while문
'''
# 1. 조건문(if문)_구문형식

if ( 조건식 ) : (콜론)
  (들여쓰기!!) ( 조건이 참일 때 수행되는 블록 )
'''

#과제1
age = int(23) 
if age < 20 :
  print('청소년 입장가능')
else :
  print('청소년 입장불가')

#input에 나이 묻도록 input 사용

age = int(input('input an age:'))
if age < 20 :
  print('입장불가')
else :
  print('입장 가능')

#들여쓰기(indentation) 블록은 매우 중요함!
#블록이란 소스코드에서 함께 묶을 수 있는 코드의 덩어리

number = int(input('정수를 입력하세요 : '))
if (number % 3) == 0 and (number % 5) == 0:
  print(number, '은(는) 3의 배수이면서 5의 배수입니다.')
else :
  print(number, '은(는) 3의 배수이면서 5의 배수가 아닙니다.')

#과제2
#입력받은 정수가 3의 배수이면 입력받은 정수  x는 3의 배수 이다
#입력받은 정수가 3의 배수가 아니면 입력받은 정수  x는 3의 배수가 아니다 
Number = int(input('정수를 입력하십시오 : '))
if (Number % 3) == 0 :
  print( '정수', Number, '은(는) 3의 배수입니다.')
else :
  print( '정수', Number, '은(는) 3의 배수가 아닙니다.')


#과제3
#윤년의 판단 기준을 조사 -> 복합조건식을 사용하여 입력한 년도가 윤년인지 아닌지를 판단.
#필수 검사연도:  2000년, 2020년
#윤년: (4로 나누어 떨어지고 100으로 나누어 떨어지거나) 또는 (400으로 나누어 떨어지면) 윤년
#방법 1(mine)
year = int(input('년도를 입력하십시오 : '))
if (year % 4 == 0) and (year % 100 == 0) :
  print( year, '은(는) 윤년입니다.')
elif (year % 400) == 0 :
  print( year, '은(는) 윤년입니다.')
else :
  print(year, '은(는) 윤년이 아닙니다.')


#방법 2(if문 2개 선택)
year = int(input('년도를 입력하십시오 : '))
if ((year % 4 == 0) and (year % 100== 0)) or (year % 400 == 0) :
  print( year, '은(는) 윤년입니다.')
else :
  print(year, '은(는) 윤년이 아닙니다.')


#짝수, 홀수 #복합조건문
a = 10
b = 14
if (a % 2 == 0) and (b % 2 == 0) :
  print('두 수 모두 짝수입니다.')
if (a % 2 == 0) or (b % 2 == 0) :
  print('두 수 중 하나 이상이 짝수입니다.')

#점수_ if else 문에 else를 사용. 
#방법 1
score = int(input('점수를 입력하십시오 : '))
if (score > 90) :
   print("A 입니다")
else :
  if (score > 80) :
    print("B 입니다.")
  else :
    print("C 입니다.")

#방법2
score = int(input('점수를 입력하십시오 : '))
if (score > 90) :
  print("A 입니다")
elif (score >= 80) :
  print("B 입니다.")
else :
  print("C 입니다.")



#윤년의 판단 기준을 조사 -> 복합조건식을 사용하여 입력한 년도가 윤년인지 아닌지를 판단.
#필수 검사연도:  2000년, 2020년
#윤년: (4로 나누어 떨어지고 100으로 나누어 떨어지거나) 또는 (400으로 나누어 떨어지면) 윤년

year = int(input('년도를 입력하십시오 : '))
if (year % 4 == 0) and (year % 100 == 0) :
  print( year, '은(는) 윤년입니다.')
elif (year % 400) == 0 :
  print( year, '은(는) 윤년입니다.')
else :
  print(year, '은(는) 윤년이 아닙니다.')

"""AI란: dataset을 이용해서 for문을 사용해 training을 시켜주는 것. <br>
학습은 learning, 어린아이는 수 많은 반복을 통해 익혀서 학습을 하게 된다. <br>
반복문: (인공지능할 때 많이 사용) 특정한 작업(기계학습, dataset 사용)을 여러 번 되풀이 해서 수행(학습)하고 싶을 경우 사용 <br>
반복문 종류: for loop, while loop <br>
for loop: 반복의 횟수가 미리 정해져 있는 경우 <br>
while loop: 반복 횟수는 알지 못하지만, 반복하는 조건이 명확한 경우에 사용. <br>
ragne: 기본 구문 <br> for i(새로운 변수) in range (n)(반복 실행 횟수) : <br>
횟수가 정해져 있거나 1씩 증가하는 숫자를 써야 할 떄 사용 <br>
i는 0부터 n-1까지 증가. <br>
"""

#과제4_자신의 이름, 학과를 키보드로 입력한 수만틈 반복 출력
num = 5 
for i in range(num) : #시작점0, 1만큼 증가
  print('정현아, 영어영문학과')


#range
#1번째와 3번째는 생략이 가능하지만, 2번째는 반드시 기입해야 한다! 
#종료값은 반환되지 않음. 
range([start,],stop, [,stop]) 

#range 함수의 활용과 리스트
list(range(0,10,2))

#1-9까지ㅣ 정수 출력
for i in range (1, 10) :
  print(i)
list(range(1,9))

#1부터 입력한 정수 n까지의 정수의 합
n = int(input('합계를 구할 수를 입력:'))
s = 0 #변수 초기화
for i range(1, n+1) :
  s = s + i
print('1에서', n '까지의 합', s)

#과제5_for문 예제(3개)
#1. 2와 7사이의 정수를 모두 출력
for i in range(2, 8) :
  print(i)
#2. 4와 4보다 큰 본인이 키보드로 입력한 정수를 모두 출력 
num =int(input('원하는 숫자를 입력하세요: ')) 
for i in range (4, num) :
  print(i)
#3. -4와 본인이 키보드로 입력한 정수를 2간격으로 모두 출력
Num =int(input('원하는 숫자를 입력하세요: ')) 
for i in range(-4,Num, 2) :
  print(i)

#과제6_for문
#1. 1부터 100사이의 수 중에서 3의 배수이면서 5의 배수인 수를 모두 더해서 출력
#반드시 for문을 사용하여 출력 
#21-10-17확인결과 츨린듯
for i in range(1, 101)
  if (i % 3 == 0) or (i % 5 == 0) :
    sum(i)

#과제6_for문
#1. 1부터 100사이의 수 중에서 3의 배수이면서 5의 배수인 수를 모두 더해서 출력
#반드시 for문을 사용하여 출력 
outcome = 0 #변수 초기화
for i in range(1, 100) :
 if (i % 3 == 0) or (i % 5 == 0):
   outcome  += i
print(outcome)

"""## 2021-09-13(목) 2주차-1차시"""

# list(C에서의 배열과 거의 동일)#tuple, #dictionary
#Today = list
# [] 사용해서 list저장, 서로 다른 종류의 자료형도 저장.
'''
for i in range(5):
  print(i)

numbers =[11,22,33,44,55,66]
for n in numbers:
  print(n, end = '')

#학번을 list에 저장하고 for문을 활용해 출력
number = [2,0,1,8,0,1,9,1]
for i in number:
  print(i, end ='')

#zip()
school = [2,0,1,8,0,1,9,1,4,5] 
birth = [1,9,9,9,0,4,1,3]
for n, v in zip(school, birth):
  print(n,v)

#tuple 
school = [2,0,1,8,0,1,9,1,4,5] 
birth = [1,9,9,9,0,4,1,3]
for pair in zip(school, birth):
  print(pair)

#tuple_numeric, string
id = [2,0,1,8] 
birth = ['A','B','C']
for pair in zip(id, birth):
  print(pair)

#for문과 enumerate()_열거_index까지 반환;tuple 형태로!)
t = [1,5,7,33,39,52]
for p in enumerate(t):
  print(p)

'''
#이중 for문
for i in range(2, 10):
  for j in range(1, 10):
    print('{}*{} = {:2d}'.format(i, j, i*j),end ='')
  print()
'''
#while문
for i in range(5):
  print("hyeonah")

i = 0
while i < 5:
  print('hyeonah')
  i += 1
  '''

"""# Practice(21-10-17)"""

# 나이에 따른 멘트
age = int("19")
if age >= 20:
  print("나이가 {}세 이시군요. 환영합니다.".format(age))
else:
  print("나이가 {}세 이시군요. 20세이상부터 입장이 가능합니다.".format(age))

# input에
 나이 묻도록 input 사용
age = int(input("나이가 어떻게 되시나요?"))
if age >= 20:
  print("나이가 {}세 이시군요. 환영합니다.".format(age))
else:
  print("나이가 {}세 이시군요. 20세이상부터 입장이 가능합니다.".format(age))

# 3의배수이면서 5의 배수인지
# num = int(input("검사를 원하는 숫자를 입력하세요"))
# if (num % 3 == 0) and (num % 5 == 0):
#   print("{}은(는) 3의배수이자 5의 배수입니다.".format(num))
# else:
#   print("{}은(는) 3의배수이자 5의 배수가 아닙니다.".format(num))
#과제2
#입력받은 정수가 3의 배수이면 입력받은 정수  x는 3의 배수 이다
#입력받은 정수가 3의 배수가 아니면 입력받은 정수  x는 3의 배수가 아니다 
Number = int(input("3의 배수인지 확인을 원하는 숫자를 입력하세요"))
if Number % 3 == 0 :
  print("{}은(는) 3의배수입니다.".format(Number))
else:
  print("{}은(는) 3의배수가 아닙니다.".format(Number))

#과제3
#윤년의 판단 기준을 조사 -> 복합조건식을 사용하여 입력한 년도가 윤년인지 아닌지를 판단.
#필수 검사연도:  2000년, 2020년
#윤년: (4로 나누어 떨어지고 100으로 나누어 떨어지거나) 또는 (400으로 나누어 떨어지면) 윤년
yr = int(input("검사를 원하는 해를 입력하세요."))
if (yr % 4 == 0) and (yr % 100 == 0):
  print(yr, "은 윤년입니다.")
elif (yr % 400 == 0):
  print(yr, "은 윤년입니다.")
else:
  print(yr, "은 윤년이 아닙니다.")

#짝수, 홀수 #복합조건문
number = int(input("숫자 입력"))
if number % 2 == 0:
  print(number, "은(는) 짝수입니다")
else:
  print(number, "은(는) 홀수입니다")

#과제4_자신의 이름, 학과를 키보드로 입력한 수만틈 반복 출력
NUM = int(input('GIve me the number'))
for i in range(NUM):
  print("Hyeonah")
  print("English Literature")

#1부터 입력한 정수 n까지의 정수의 합
n = int(input('GIve number'))
s = 0 
for i in range(1, n+1):
  s = s + i 
print(s)

# #1. 2와 7사이의 정수를 모두 출력
# for i in range (2, 8):
#   print(i)


# #2. 4와 4보다 큰 본인이 키보드로 입력한 정수를 모두 출력 
# F = int(input("숫자: "))
# for i in range(4, F+1):
#   print(i)


# #3. -4와 본인이 키보드로 입력한 정수를 2간격으로 모두 출력
# G = int(input("숫자: "))
# for i in range (-4, G, 2):
#   print(i)


#과제6_for문
#1. 1부터 100사이의 수 중에서 3의 배수이면서 5의 배수인 수를 모두 더해서 출력
#반드시 for문을 사용하여 출력 
v = 0 
for i in range (1, 101):
  if i % 3 == 0 and i % 5 == 0:
    v = i + v  # v += i와 동일
print(v)

# list 연습
numbers =[11,22,33,44,55,66]
for n in numbers:
  print(n, end = '') # 띄어쓰기 없음

#학번을 list에 저장하고 for문을 활용해 출력
list = [2,0,1,8,0,1,9,1]
for i in list:
  print(i)

#tuple_numeric, string
id = [2,0,1,8] 
birth = ['A','B','C']
for i in zip(id, birth):
  print(i)

#for문과 enumerate()_열거_index까지 반환;tuple 형태로!)
t = [1,5,7,33,39,52]
for p in enumerate(t):
  print(p)

#이중 for문
for i in range(2, 10):
  for j in range(1, 10):
    print('{}*{} = {:2d}'.format(i, j, i*j),end ='')
print()