# -*- coding: utf-8 -*-
"""21-12-02_pytorch.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ukj9CD27WcE1oKz67oAkaLfQh_fz4Up6
"""

import torch

x = torch.empty(5,3)
x

y = torch.tensor([[1.2,3],[3, 5.5]])
y

a = [[1.0, 2.0], [3.0, 1.0], [2.5, 1.5]]
tensor = torch.tensor(a)
tensor

