# -*- coding: utf-8 -*-
"""21-11-25_Regression.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YZmxCgwy36fWwLfqqzksJdO-Vchb3yYQ
"""

import matplotlib.pyplot as plt
import pandas as pd

# 데이터 저장 위치
data_home = 'https://github.com/dknife/ML/raw/main/data/'
lin_data = pd.read_csv(data_home+"pollution.csv")
print(lin_data)

lin_data.plot(kind = "scatter", x = "input", y = "pollution")

w,b = 1, 1
x0, x1 = 0.0, 1.0
def h(x, w, b):
  return w*x +b

lin_data.plot(kind = "scatter", x = "input", y = "pollution")
plt.plot([x0,x1], [h(x0, w, b), h(x1, w, b)])

w,b = -5.5, 5.5
x0, x1 = 0.0, 1.0
def h(x, w, b):
  return w*x +b

lin_data.plot(kind = "scatter", x = "input", y = "pollution")
plt.plot([x0,x1], [h(x0, w, b), h(x1, w, b)])

# 모델의 오차
import numpy as np
y_hat = np.array([1.2, 2.1,2.9, 4.1, 4.7, 6.3, 7.1, 7.7, 8.5, 10.1]) #모델에 대한 데이터
y = np.array([1,2,3,4,5,6,7,8,9,10])# 샘플 데이터
diff_square = (y_hat - y)**2
e_mse = diff_square.sum() /len(y)
e_mse

