# -*- coding: utf-8 -*-
"""21-11-11.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1g6PyQJukEgaPiYQVUVI9Z3ygyXgy8TMh

# 수업 1
"""

import pandas as pd
path = 'http://github.com/dknife/ML/raw/main/data/'
file = path +'vehicle_prod.csv'

df = pd.read_csv(file)
print(df)

df = pd.read_csv(file, index_col = 0)
print(df)

# df = pd.read_csv(file, index_col = 2)
# print(df)

# 특정 열만 출력
df_my_index = pd.read_csv(file, index_col = 0)
df_no_index = pd.read_csv(file)
print(df_my_index['2007'])
print(df_no_index['2007'])

# 원하는 열들의 레이블을 리스트로 
print(df[['2007','2008','2009']])

# 그래프 그리기
import matplotlib.pyplot as plt
df['2009'].plot(kind='bar', color=('orange','r','b','m','c','k'))

df.plot()

"""# 과제1_dataframe 만들고 matplot"""

data = pd.DataFrame([[103,178],
              [363,	289],
              [151,97],
              [154,232],
              [88,129]],
            #  index = [[swimming, baseball, golf, soccer, bowling],
             columns= ['Male', 'Female'])

 pop_df
# index = [swimming, baseball, golf, soccer, bowling])
# gender = 
# sports

df = pd.DataFrame({'Male': [103,363,151,154,88],
                   'Female': [178,289,97,232,129]},
                  index = ['swimming', 'baseball', 'golf', 'soccer', 'bowling'])
df

df.plot(kind ='bar')

df.plot(kind ='barh')

df.plot(kind ='bar', stacked=True)

"""# 수업 이어서 2"""

# usa, mexico
df['2010'][[2,5]]

df.loc["US", "2009"]

path = 'http://github.com/dknife/ML/raw/main/data/'
weather_file = path + 'weather.csv'
weather = pd.read_csv(weather_file, index_col=0,encoding = 'CP949')
print(weather.head(3))

weather.describe()

"""# 과제5 _concat()


"""

import pandas as pd
df1 = pd.DataFrame({'A': ['A1','A2','A3'],
                   'B': ['B1','B2','B3'],
                   'C': ['C1','C2','C3']},
                  index = ['ONE', 'TWO', 'THREE'])
print(df1)

df2 = pd.DataFrame({'C': ['C2','C3','C4'],
                   'D': ['D2','D3','D4']},
                  index = ['TWO', 'THREE','FOUR'])
print(df2)

s1 = pd.Series(['X1','X2','X3'],
 index=['ONE','TWO', 'THREE'])
print(s1)

s2 = pd.Series(['Y2','Y3','Y4'],
 index=['TWO', 'THREE','FOUR'])
print(s2)

pd.concat([df1,df2])

pd.concat([df1,df2],axis = 1)

pd.concat([s1,s2])

pd.concat([df1,s2])

df4 = pd.concat([df1,s2], axis =1)
df4.columns = ['A', 'B', 'C', 'Y']
df4

