# -*- coding: utf-8 -*-
"""21-10-18_live coding.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1K_CM-4C3rXstvKdKBhbgZhedJfLpqZ0m

## 21-10-18 Live coding test
"""

# 1번 문제
def star():
  n = int(input('숫자를 입력하세요 '))
  for i in range(n+1):
    print(' '*(n-i), end ='')
    print('*'*i)
star()

# 2번 문제
a = ['My ', 'favorite ', 'language ', 'is ', 'Python']
a.append(" or C")
for i in a:
  print(i, end ='')
# a = ''.join(a)
# print(a)

# 3번 문제
# (a)
import numpy as np
a= [0, 1, -3, 5, 4, 9, -1, 6, 3]
np.array([0, 1, -3, 5, 4, 9, -1, 6, 3])

# (b)
c = np.array(a).reshape(3, 3)
print(c)

# (c)
print(c[1:,1:])

# (d) # 이건 제출못하고, 끝나고 확인 한 것
d = np.array(c[1:,1:])
d.sum(axis=0)

# 4번 문제
kor =  'Chosun', 'SNU', 'Yonsei'
asia= 'Peking', 'Tsinghwa', 'Sanghai'
america = 'Harvard', 'MIT', 'Stanford'
kor =  list(kor)
asia = list(asia)
america = list(america)
# (a) 미국 대학만 출력
print(america) # ['Harvard', 'MIT', 'Stanford']

# (b) 각 지역의 2위대학만 출력
univs = [['Chosun', 'SNU', 'Yonsei'],['Peking', 'Tsinghwa', 'Sanghai'],['Harvard', 'MIT', 'Stanford']]
t = [ ]
for i in univs:
  t.append(i[1])
print(t) #['SNU', 'Tsinghwa', 'MIT']

