# -*- coding: utf-8 -*-
"""21-11-15_matplotlib.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_Hh5wnqQeKqlBZYNccQYuMZr062qv4hA
"""

import matplotlib.pyplot as plt
plt.plot([1,2,3,4])
plt.ylabel('y-numbers')
plt.show()

import matplotlib.pyplot as plt
plt.plot([1,2,3,6])
plt.ylabel('y-numbers')
plt.show()

import matplotlib.pyplot as plt
plt.plot([1,2,3,4],[1,4,9,16])
plt.xlabel('X-numbers')
plt.ylabel('Y-numbers')
plt.show()

import matplotlib.pyplot as plt
plt.plot([1,2,3,4],[1,4,9,16], 'ro') # red circle
plt.xlabel('x-numbers')
plt.ylabel('y-numbers')
plt.axis([0,6,0,20])
plt.show()

import matplotlib.pyplot as plt
plt.plot([1,2,3,4],[1,4,9,16], 'bo') # blue circle
plt.xlabel('x-numbers')
plt.ylabel('y-numbers')
plt.axis([0,5,0,17])
plt.show()

import matplotlib.pyplot as plt
import numpy as np
t = np.arange(0.,5.,0.2)
t

t = np.linspace(0,5,50)
t

import matplotlib.pyplot as plt
import numpy as np
t = np.arange(0.,5.,0.2)
plt.plot(t, t, 'r--')
plt.plot(t, t**2, 'bs')
plt.plot(t, t**3, 'g^')
plt.show()

import matplotlib.pyplot as plt
import numpy as np
t = np.arange(0.,5.,0.2)
plt.plot(t, t, 'r--')
plt.plot(t, t**2, 'bs')
plt.plot(t, t**3, 'g^')
plt.axis([0, 4,0, 40]) # 확대!
plt.show()

# lengend 범례
import matplotlib.pyplot as plt
plt.plot([1,2,3,4],[2,3,5,10], label='price = ($)')
plt.xlabel('X-Axis')
plt.ylabel('Y-Axis')
plt.legend()
plt.show()

import matplotlib.pyplot as plt
plt.plot([1,2,3,4],[2,3,5,10], label='price = ($)')
plt.xlabel('X-Axis')
plt.ylabel('Y-Axis')
plt.legend(loc =(0.1,0.5))
plt.show()

# 선종류 지정
import matplotlib.pyplot as plt

plt.plot([1,2,3],[4,4,4],'-', color ='r', label = 'Solid')
plt.plot([1,2,3],[3,3,3],'--', color ='C0', label = 'Dashed')
plt.plot([1,2,3],[2,2,2],':', color ='b', label = 'Dotted')
plt.plot([1,2,3],[1,1,1],'-.', color ='C0', label = 'Daxh-dot')
plt.xlabel('X-Axis')
plt.ylabel('Y-Axis')
plt.axis([0.8,3.2,0.5,5.0])
plt.legend(loc='upper right', ncol = 4)
plt.show()

import matplotlib.pyplot as plt

plt.plot([1,2,3],[4,4,4],'-', color ='r', label = 'Solid')
plt.plot([1,2,3],[3,3,3],'--', color ='C0', label = 'Dashed')
plt.plot([1,2,3],[2,2,2],':', color ='b', label = 'Dotted')
plt.plot([1,2,3],[1,1,1],'-.', color ='C0', label = 'Daxh-dot')
plt.xlabel('X-Axis')
plt.ylabel('Y-Axis')
plt.axis([0.8,3.2,0.5,5.0])
plt.legend(loc='upper right', ncol = 1)
plt.show()

# 활용
import matplotlib.pyplot as plt
plt.plot([1,2,3,4],[2,3,10,12])
plt.plot([1,2,3,4],[3,6,9,12], 'ro') # red circle
t = np.arange(0.,5.,0.2)
plt.plot([1,2,3,4],[3,6,9,12], 'bo') # square
plt.xlabel('X-Axis')
plt.ylabel('Y-Axis')
plt.show()

# 색상 지정
# 활용
import matplotlib.pyplot as plt
plt.plot([1,2,3,4],[2.0,3.0,5.0,10.0], color ='seagreen')
plt.plot([1,2,3,4],[2.0,2.8,4.6,6.5], color = 'peru') 
plt.plot([1,2,3,4],[2.0,2.5,3.3,4.5], 'r')
plt.xlabel("x-axis")
plt.ylabel("y-axis")
plt.show()

# 여러 그래프 그리기 1
import matplotlib.pyplot as plt
import numpy as np
x = np.arange(0,2,0.2)
plt.plot(x,x,'r--',x,x**2, 'bo',x,x**3,'g-.')
plt.show()

# 여러 그래프 그리기 2
import matplotlib.pyplot as plt
import numpy as np

x = np.arange(0,2,0.2)

plt.plot(x,x,'bo')
plt.plot(x,x**2, color = 'seagreen', marker = '*', linewidth =2)
plt.plot(x,x**3, color = 'peru', marker = '^', linewidth =9)
plt.show()

# scatter 산점도
import matplotlib.pyplot as plt
import numpy as np

np.random.seed(0)
n = 50
x = np.random.rand(n)
y = np.random.rand(n)
plt.scatter(x,y)
plt.show()

# scatter 산점도 2
import matplotlib.pyplot as plt
import numpy as np

np.random.seed(0)
n = 50
x = np.random.rand(n)
y = np.random.rand(n)
area = (30 * np.random.rand(n)) **2
colors = np.random.rand(n)
plt.scatter(x,y, s = area, c = colors)
plt.scatter(x,y)
plt.show()

# histogram
import matplotlib.pyplot as plt
weight = [68,81,64,56,78,74,61,77,66,68,59,71,80,59,67,81,69,73,69,74,70,65]
plt.hist(weight)
plt.show()

import matplotlib.pyplot as plt
weight = [68,81,64,56,78,74,61,77,66,68,59,71,80,59,67,81,69,73,69,74,70,65]
plt.hist(weight, label = 'bins=10')
plt.hist(weight, bins = 30, label = 'bins=30')
plt.legend()
plt.show()

# 사인 함수
import matplotlib.pyplot as plt
import numpy as np

X = np.linspace(0,4*np.pi,200)
Y = np.sin(X)
plt.plot(X,Y)
plt.show()

# 사인 함수 2
import matplotlib.pyplot as plt
import numpy as np

# 파란색 = sin 함수
X = np.linspace(0,4*np.pi,200)
Y = np.sin(X)
plt.plot(X,Y)

# 노란색 = cos 함수
Z = np.linspace(0,4*np.pi,200)
F = np.cos(Z)
plt.plot(Z,F)
plt.show()

