# -*- coding: utf-8 -*-
"""Homework2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1n4UqUES1ovODuC0iFia2Mz3kY6E29gFC
"""

















