# -*- coding: utf-8 -*-
"""prep_hw2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kfk-VNgqJPncXRGurBi3XIPgUMvhhW9Q
"""

#7
num = [1,9,9,9,0,4,1,3,2,0,1,8,0,1,9,1]

for i in range(len(num)):
  h = len(num) - i
  for z in range(1, h):
      if num[z-1] >= num[z]:
        temp = num[z-1]
        num[z-1] = num[z]
        num[z] = temp
print(num)

#7
num = [1,9,9,9,0,4,1,3,2,0,1,8,0,1,9,1]

for i in range(len(num)):
  h = len(num) - i
  for z in range(1, h):
      if num[z-1] >= num[z]:
        temp = num[z-1]
        num[z-1] = num[z]
        num[z] = temp
print(num)

l = [1,9,9,9,0,4,1,3,2,0,1,8,0,1,9,1]
for j in range(len(l)):
    k = len(l) - j
    for i in range(1, k):
        if l[i-1] >= l[i]:
            temp = l[i-1]
            l[i-1] = l[i]
            l[i] = temp

print(l)

# 1) 100만원 이상 원금, 이율, 기간 입력받기
# 2) 1)에 맞는 조건 입력받으면, 원리금(원금+이자)출력.
# 출력예시에서 원리금을 출력하고 있음 -> 즉, 원금+이자의 합계를 출력하는 것이 문제의 요점.
# 복리 계산 공식:  현재가치 * ((1+금리) ** 기간)
org = int(input("원금(단위:원)을 입력하세요 : "))
if org >= 100 :
    perc = int(input("이율(%)을 입력하세요 : "))
    year = int(input("기간(년)을 입력하세요 : "))
    PnI = org * ((1+perc*0.01)**year)
    print(PnI)
else :
    print("잘못된 입력입니다. 1,000,000원 이상 입력해주세요.")

계산 예시
#원금 120만원, year 2, 이율 3
#복리
#공식:  현재가치 * ((1+금리) ** 기간)
z = 1200000*((1+0.03)**2)
print(z)