# -*- coding: utf-8 -*-
"""CDS_IDS.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UaGEd4YGRvDt7i-sXUXT8A-at6_0IXH2
"""

#f = open("2_complete.txt", 'r')
#line = f.readline()
#print(line)
# 모든 줄 읽어들이기
#while True:
#    line = f.readline()
#    if not line: break
#    print(line)
#f = open("2_complete.txt", 'r')

# sentence 추출
#while True:
#  i = 5
#  print(intervals, text)

# 한 줄씩 추출
#f.readline()

# 한 줄 한 줄을 리스트로 저장
#f = open("2_complete.txt")
#lines = f.readlines()
#lines[-1 # 제일 마지막줄 추출]

# 문자 "korean"이 있는 줄만 표시
f = open("2_complete.txt")
lines = f.readlines()
for line in open("2_complete.txt"):
  if "Korean" in line:
    print(line)

# sil 제거하고 싶다면
#for line in open("palc.log"):
#  if "sil" in line:
#    print(line.replace("test=", ""))

# findstr, grep ?

import pandas as pd
line

xy = np.loadtxt('d2_complete.txt', delimiter=',',dtype=np.,encoding =UTF-8)
print(xy)
x = xy[0:5]
print(x)

# read file
file = open( "3_complete.txt","r", encoding='utf-8', errors='ignore')
lines = file.readlines()
file.close

# <the readlines() method to read the text file and returns the file contents as a list of strings>
# count = 0
# for line in lines:
#     count += 1
#     print(f'line {count}: {line}')

# <look for patterns>
# for line in lines:
#  line = line.strip()
#  if line.find( "Korean") != -1:
#    print(line)

# <Process>
# 1.  korean이 시작하는 줄 번호 찾는 함수 생성
def find_line():
  count = 0
  for line in lines:
   count += 1
   line = line.strip()
   if line.find( "Korean") != -1:
     line.find("text")
     print(f'line {count}: {line}')
    
find_line()

# 2. vlaue값에 1번 값(Korean 시작 줄 번호)입력 
value = 67492
lines2 = (lines[67492:-1])

# # 3. [korean~끝] 중에서 text만을 추출 (sil도 아직은 추출)
# for i in lines2:
#   if i.find("text")!= -1:
#     print(f'line {count}: {i}')

# 3. [korean~끝] 중에서 text만을 추출 + line은 안나오게  (sil도 아직은 추출)
for i in lines2:
  if i.find("text")!= -1:
    print(i)

#read file
file = open("2_complete.txt","r", encoding='utf-8', errors='ignore')
lines = file.readlines()
file.close

# 1.  korean이 시작하는 줄 번호 찾는 함수 생성
def find_line():
  count = 0
  for line in lines:
   count += 1
   line = line.strip()
   if line.find( "Korean") != -1:
     line.find("text")
     print(f'line {count}: {line}')    
find_line()

 # 2. vlaue값에 1번 값(Korean 시작 줄 번호)입력 
value = 76472
lines2 = (lines[76472:-1])

# 3. [korean~끝] 중에서 text만을 추출 (sil도 아직은 추출)
for i in lines2:
  if i.find("text")!= -1:
    print(i)