# -*- coding: utf-8 -*-
"""로또.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aeiuYGkG9XUtW9gS3nNL1ge3OC1SM6vc
"""

# a, b, c, d, e, f = map(int, input().split())
lottos = input().split()
win_nums = input().split()


def solution(lottos, win_nums):
  answer = []
  zeros = 0
  tmp = 0
  for i, l in enumerate(lottos): #index = i, value = l
      if l in win_nums: # 당첨번호에 lottos 번호가 있으면
          tmp += 1    # tmp에 1씩 추가
      if l == 0:  # lottos 번호가 0이면
          zeros += 1  # zeros에 1씩 추가

  if not zeros and not tmp: # 0도 아니고 일치하는 번호도 없으면
      answer.append(6) # max= answer은 6, 즉 6등
  else:
      answer.append(7 - (tmp+zeros)) # max=나머지
  if tmp == 0: # min=맞는게 하나도 없으면 6등
      answer.append(6)
  else:
      answer.append(7 - tmp) # min= 0은 틀린 것으로 간주하고, lottos와 win_num이 일치하는 것만 갯수로 인정


  return answer

solution(lottos, win_nums)

